
from network.regularizer.weight_decay import WeightDecay
from network.regularizer.scale_invariant import ScaleInvariant
from network.regularizer.offset_invariant import OffsetInvariant
from network.regularizer.rotation_invariant import RotationInvariant
